sudo: false

language: node_js

node_js:
    - '10'

notifications:
    email: false

cache:
    yarn: true
    directories:
        - node_modules

branches:
    only:
        - master

before_install: yarn global add greenkeeper-lockfile@1

install: yarn

before_script: greenkeeper-lockfile-update

script:
    - yarn test:ci

after_script: greenkeeper-lockfile-upload

after_success:
    - yarn semantic-release
